### ISSUE TITLE
Server Crash due to dying with totem of undying in inventory

### ISSUE THREAD

**Issue by kaeebonrai** [Vazkii/crucia2-issues#64] opened 2021-02-19 16:15 UTC
Raids are unable to be completed due to continual crashing from this bug.
[debug.log](https://github.com/Vazkii/crucia2-issues/files/6011231/debug.log)
[latest.log](https://github.com/Vazkii/crucia2-issues/files/6011232/latest.log)
[crafttweaker.log](https://github.com/Vazkii/crucia2-issues/files/6011234/crafttweaker.log)
[crash-2021-02-13_06.56.47-server.txt](https://github.com/Vazkii/crucia2-issues/files/6011236/crash-2021-02-13_06.56.47-server.txt)

**Comment by Vazkii** [comment] 2021-02-19 17:50
Dupe of #63

**Closed by Vazkii** 2021-02-19 17:50 UTC
